1. Crear un vector con valores dentro del rango 10 a 49.

In [6]:
import numpy as np

vector = np.arange(10, 50) #arange sirve para crear vectores, se entrega el rango sumándole 1 al final
vector

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

4. Crea un arreglo NumPy de tamaño 5x5 lleno de ceros.

In [16]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

5. Crea un arreglo NumPy de tamaño 3x3 lleno de unos.

In [17]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

7. Genera una matriz de tamaño 5x5 con valores aleatorios enteros
entre 1 y 100.


In [28]:
print(np.random.randint(1,100,(5,5)))


[[97 86 31 20 18]
 [85 79 27 49 21]
 [69 37 24 39  6]
 [84 70  4 75 54]
 [46 87 76 49 31]]


10. Crear un arreglo con elementos del 1 al 10 y seleccionar solo los pares

In [13]:
arreglos_pares = np.arange(1, 11)
print(arreglos_pares[(arreglos_pares % 2 == 0)])



[ 2  4  6  8 10]
